apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-backend
  template:
    metadata:
      labels:
        app: ai-backend
    spec:
      containers:
      - name: ai-backend
        image: your-docker-user/ai-backend:latest
        ports:
        - containerPort: 5000
